//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Part Picker&lt;/title&gt;
        ///    &lt;style&gt;
        ///        &lt;![CDATA[STYLESHEET]]&gt;
        ///    &lt;/style&gt;
        ///    &lt;script language=&quot;javascript&quot;&gt;
        ///        &lt;![CDATA[JAVASCRIPT]]&gt;
        ///    &lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;ul id=&quot;view&quot;&gt;
        ///        
        ///    &lt;/ul&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string BlankBrowser {
            get {
                return ResourceManager.GetString("BlankBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;database&gt;
        ///  &lt;type name=&quot;Processor&quot;&gt;
        ///    &lt;property name=&quot;Frequency&quot; type=&quot;number&quot; /&gt;
        ///    &lt;property name=&quot;Cores&quot; type=&quot;number&quot; /&gt;
        ///  &lt;/type&gt;
        ///  
        ///  &lt;type name=&quot;Memory&quot;&gt;
        ///    &lt;property name=&quot;Frequency&quot; type=&quot;number&quot; /&gt;
        ///    &lt;property name=&quot;Size&quot; type=&quot;number&quot; /&gt;
        ///  &lt;/type&gt;
        ///  
        ///  &lt;type name=&quot;Power Source&quot; /&gt;
        ///  
        ///  &lt;type name=&quot;Motherboard&quot;&gt;
        ///  &lt;/type&gt;
        ///  
        ///  &lt;type name=&quot;Disk&quot;&gt;
        ///    &lt;property name=&quot;HDD/SSD&quot; type=&quot;string&quot; /&gt;
        ///    &lt;property name=&quot;Speed&quot; type=&quot;string&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankDatabase {
            get {
                return ResourceManager.GetString("BlankDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///    buildView();
        ///});
        ///
        ///function buildView()
        ///{
        ///    if (window.external.IsEmpty())
        ///    {
        ///        $(&quot;#view&quot;).html(&quot;&lt;center&gt;This build is currently empty.&lt;br/&gt;To start, &lt;button onclick=&apos;findComponentsByType(\&quot;Power Source\&quot;)&apos;&gt;Add a Power Source&lt;/button&gt;&lt;/center&gt;&quot;);
        ///    }
        ///    else
        ///    {
        ///        window.external.RefreshBrowser();
        ///    }
        ///}
        ///
        ///function setView(html)
        ///{
        ///    $(&quot;#view&quot;).html(html);
        ///}
        ///.
        /// </summary>
        internal static string BrowserScript {
            get {
                return ResourceManager.GetString("BrowserScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///    font: 13px Calibri, Arial, sans-serif;
        ///    color: black;
        ///    background-color: white;
        ///    margin: 10px;
        ///    padding: 0;
        ///}
        ///
        ///button
        ///{
        ///    width: auto;
        ///    margin: 5px;
        ///    color: white;
        ///    border: none;
        ///    background-color: #282828;
        ///    font: 13px Calibri, Arial, sans-serif;
        ///    cursor: pointer;
        ///
        ///}
        ///
        ///ul
        ///{
        ///    margin: auto;
        ///    width: 100%;
        ///    position: relative;
        ///}
        ///
        ///h2
        ///{
        ///    font-weight: normal;
        ///    display: inline;
        ///}
        ///
        ///ul
        ///{
        ///    margin-left: 15px;
        ///}
        ///
        ///ul#view
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrowserStyle {
            get {
                return ResourceManager.GetString("BrowserStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connector_left {
            get {
                object obj = ResourceManager.GetObject("connector_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connector_right {
            get {
                object obj = ResourceManager.GetObject("connector_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.3 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.3&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_11_3_min {
            get {
                return ResourceManager.GetString("jquery_1_11_3_min", resourceCulture);
            }
        }
    }
}
